# Generated by Django 4.2 on 2023-10-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_collage_branch',
            name='collage_name',
        ),
        migrations.RemoveField(
            model_name='add_student',
            name='branch_name',
        ),
        migrations.DeleteModel(
            name='Add_Collage',
        ),
        migrations.DeleteModel(
            name='Add_Collage_Branch',
        ),
        migrations.DeleteModel(
            name='Add_Student',
        ),
    ]
