# Generated by Django 4.2 on 2023-10-28 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mydata', '0009_remove_add_collage_branch_collage_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collage_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Add_Collage_Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100, unique=True)),
                ('collage_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydata.add_collage', to_field='collage_name')),
            ],
        ),
        migrations.CreateModel(
            name='Add_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_age', models.IntegerField()),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydata.add_collage_branch', to_field='branch_name')),
                ('collage_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydata.add_collage', to_field='collage_name')),
            ],
        ),
    ]
